# Stage-1 & specify a name 'builder'

FROM node:latest AS builder

# Create a directory and go to the directory
WORKDIR /app

# Copy the package.json file to my current directory to install the necessary dependencies
COPY package*.json /app/

# Install the dependencies
RUN npm install -g vite && npm install

# Copy other files to my current directory
COPY . .

# Open the react dev port
EXPOSE 5173

# run react dev server
CMD ["npm", "run", "dev"]