// variables
@HOST=localhost:3000
###
// signup (create user)
POST http://{{HOST}}/api/users/signup HTTP/1.1
Accept: */*
Content-Type: application/json

{
  "name": "elias",
  "secret": "eliaspass",
  "email": "elias@elias.com",
  "image": "https://avatars.githubusercontent.com/u/92063279"
}
###
// login
POST http://{{HOST}}/api/users/login HTTP/1.1
Accept: */*
Content-Type: application/json

{
  "email":"ben@ben.com",
  "secret":"benpass"
}
###
// get all users
GET http://{{HOST}}/api/users/ HTTP/1.1
Accept: */*
Content-Type: application/json

{
  "name":"elias",
  "secret":"eliaspass"
}